name: fill in hb sales column

on:
  workflow_dispatch:
  # Optional schedule
  # schedule:
    #- cron: "0 10 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            gspread \
            pandas \
            google-auth \
            google-api-python-client \
            openpyxl

      - name: get metas from the filial sheets
        env:
          GSA_CREDENTIALS: ${{ secrets.GSA_CREDENTIALS }}
          SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
          TARGET_SHEETS_CONFIG: ${{ secrets.TARGET_SHEETS_CONFIG }}
        run: |
          python hb_run.py
